// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DeploymentInfoStatus.
const (
	DeploymentInfoStatusRunning  DeploymentInfoStatus = "running"
	DeploymentInfoStatusStarting DeploymentInfoStatus = "starting"
	DeploymentInfoStatusStopping DeploymentInfoStatus = "stopping"
)

// Defines values for ErrorDeploymentInfoPreviousStatus.
const (
	ErrorDeploymentInfoPreviousStatusStarting ErrorDeploymentInfoPreviousStatus = "starting"
	ErrorDeploymentInfoPreviousStatusStopping ErrorDeploymentInfoPreviousStatus = "stopping"
)

// Defines values for RetryDeploymentRequestAction.
const (
	Delete    RetryDeploymentRequestAction = "delete"
	Deploy    RetryDeploymentRequestAction = "deploy"
	Terminate RetryDeploymentRequestAction = "terminate"
)

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusError    StatusResponseStatus = "error"
	StatusResponseStatusRunning  StatusResponseStatus = "running"
	StatusResponseStatusStarting StatusResponseStatus = "starting"
	StatusResponseStatusStopping StatusResponseStatus = "stopping"
)

// AdminDeployRequest defines model for AdminDeployRequest.
type AdminDeployRequest struct {
	// Category The category of the challenge to deploy.
	Category string `json:"category"`

	// ChallengeName The name of the challenge to deploy.
	ChallengeName string `json:"challenge_name"`
}

// BulkOperationResponse defines model for BulkOperationResponse.
type BulkOperationResponse struct {
	Challenges      []ChallengeCategoryResponse `json:"challenges"`
	ChallengesCount int                         `json:"challenges_count"`
	Message         string                      `json:"message"`
}

// ChallengeCategoryResponse defines model for ChallengeCategoryResponse.
type ChallengeCategoryResponse struct {
	Category      string `json:"category"`
	ChallengeName string `json:"challenge_name"`
}

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	// Category The category of the challenge to deploy.
	Category string `json:"category"`

	// ChallengeName The name of the challenge to deploy.
	ChallengeName string `json:"challenge_name"`
}

// DeploymentInfo defines model for DeploymentInfo.
type DeploymentInfo struct {
	Category       string  `json:"category"`
	ChallengeName  string  `json:"challenge_name"`
	ConnectionInfo *string `json:"connection_info,omitempty"`

	// DeployedDurationSeconds Duration in seconds since deployment started.
	DeployedDurationSeconds int `json:"deployed_duration_seconds"`

	// DeployedSince The time the deployment was created.
	DeployedSince time.Time `json:"deployed_since"`

	// ExpiresAt When the deployment expires. Null for unique deployments.
	ExpiresAt *time.Time           `json:"expires_at,omitempty"`
	Status    DeploymentInfoStatus `json:"status"`
}

// DeploymentInfoStatus defines model for DeploymentInfo.Status.
type DeploymentInfoStatus string

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// ErrorDeploymentInfo defines model for ErrorDeploymentInfo.
type ErrorDeploymentInfo struct {
	Category      string `json:"category"`
	ChallengeName string `json:"challenge_name"`

	// CreatedAt When the deployment was created.
	CreatedAt time.Time `json:"created_at"`

	// ErrorMessage The error message from the failed deployment.
	ErrorMessage string `json:"error_message"`

	// Id The deployment ID.
	Id int `json:"id"`

	// PreviousStatus The status before the deployment transitioned to error. Indicates whether a deploy or terminate action was in progress.
	PreviousStatus ErrorDeploymentInfoPreviousStatus `json:"previous_status"`

	// TeamId The team identifier. Empty string for unique/admin deployments.
	TeamId string `json:"team_id"`

	// UpdatedAt When the deployment was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ErrorDeploymentInfoPreviousStatus The status before the deployment transitioned to error. Indicates whether a deploy or terminate action was in progress.
type ErrorDeploymentInfoPreviousStatus string

// ReloadChallengesResponse defines model for ReloadChallengesResponse.
type ReloadChallengesResponse struct {
	// Indexed Number of challenges in the index after the reload.
	Indexed int `json:"indexed"`

	// Skipped Challenge files left out of the index.
	Skipped []SkippedChallenge `json:"skipped"`
}

// RetryDeploymentRequest defines model for RetryDeploymentRequest.
type RetryDeploymentRequest struct {
	// Action The action to perform - 'deploy' to retry deployment, 'terminate' to terminate the failed deployment, 'delete' to remove the deployment from the database. If not provided, the action will be inferred from the previous status (deploy or terminate only).
	Action *RetryDeploymentRequestAction `json:"action,omitempty"`

	// DeploymentId The ID of the deployment to retry.
	DeploymentId int `json:"deployment_id"`
}

// RetryDeploymentRequestAction The action to perform - 'deploy' to retry deployment, 'terminate' to terminate the failed deployment, 'delete' to remove the deployment from the database. If not provided, the action will be inferred from the previous status (deploy or terminate only).
type RetryDeploymentRequestAction string

// SkippedChallenge defines model for SkippedChallenge.
type SkippedChallenge struct {
	// Path Path of the challenge file.
	Path string `json:"path"`

	// Reason Why it was skipped.
	Reason string `json:"reason"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ConnectionInfo *string    `json:"connection_info,omitempty"`
	ExpirationTime *time.Time `json:"expiration_time,omitempty"`

	// ExtensionTime Time duration each extension adds (e.g., "30m", "1h").
	ExtensionTime *string `json:"extension_time,omitempty"`

	// ExtensionsLeft Number of extensions left for this deployment. -1 if unlimited.
	ExtensionsLeft *int                  `json:"extensions_left,omitempty"`
	Status         *StatusResponseStatus `json:"status,omitempty"`

	// Unique Whether this is a unique deployment or not.
	Unique *bool `json:"unique,omitempty"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// TeamDeploymentsResponse defines model for TeamDeploymentsResponse.
type TeamDeploymentsResponse struct {
	Deployments []DeploymentInfo `json:"deployments"`

	// TeamId The team identifier. Empty string for unique/admin deployments.
	TeamId string `json:"team_id"`
}

// DeployAdminInstanceJSONRequestBody defines body for DeployAdminInstance for application/json ContentType.
type DeployAdminInstanceJSONRequestBody = AdminDeployRequest

// RetryDeploymentJSONRequestBody defines body for RetryDeployment for application/json ContentType.
type RetryDeploymentJSONRequestBody = RetryDeploymentRequest

// TerminateAdminInstanceJSONRequestBody defines body for TerminateAdminInstance for application/json ContentType.
type TerminateAdminInstanceJSONRequestBody = AdminDeployRequest

// DeployInstanceJSONRequestBody defines body for DeployInstance for application/json ContentType.
type DeployInstanceJSONRequestBody = DeployRequest

// TerminateInstanceJSONRequestBody defines body for TerminateInstance for application/json ContentType.
type TerminateInstanceJSONRequestBody = DeployRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check communication with Zync
	// (POST /admin/config-check)
	ConfigCheck(ctx echo.Context) error
	// Deploy a unique challenge (admin only)
	// (POST /admin/deploy)
	DeployAdminInstance(ctx echo.Context) error
	// Deploy all unique challenges (admin only)
	// (POST /admin/deploy-all)
	DeployAllAdminInstances(ctx echo.Context) error
	// List all deployments in error status (admin only)
	// (GET /admin/error-deployments)
	ListErrorDeployments(ctx echo.Context) error
	// List all unique challenges
	// (GET /admin/list-unique-challs)
	ListUniqueChallenges(ctx echo.Context) error
	// Reload challenges index
	// (POST /admin/reload-challs)
	ReloadChallenges(ctx echo.Context) error
	// Retry a failed deployment (admin only)
	// (POST /admin/retry-deployment)
	RetryDeployment(ctx echo.Context) error
	// List all deployments grouped by team (admin only)
	// (GET /admin/team-deployments)
	ListTeamDeployments(ctx echo.Context) error
	// Terminate a unique challenge (admin only)
	// (POST /admin/terminate)
	TerminateAdminInstance(ctx echo.Context) error
	// Terminate all unique challenges (admin only)
	// (POST /admin/terminate-all)
	TerminateAllAdminInstances(ctx echo.Context) error
	// Deploy a challenge instance
	// (POST /deploy)
	DeployInstance(ctx echo.Context) error
	// Extend the duration of a deployment
	// (POST /extend)
	ExtendInstance(ctx echo.Context) error
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Get deployment status
	// (GET /status)
	GetInstanceStatus(ctx echo.Context) error
	// Terminate a challenge instance
	// (POST /terminate)
	TerminateInstance(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ConfigCheck converts echo context to params.
func (w *ServerInterfaceWrapper) ConfigCheck(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfigCheck(ctx)
	return err
}

// DeployAdminInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeployAdminInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployAdminInstance(ctx)
	return err
}

// DeployAllAdminInstances converts echo context to params.
func (w *ServerInterfaceWrapper) DeployAllAdminInstances(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployAllAdminInstances(ctx)
	return err
}

// ListErrorDeployments converts echo context to params.
func (w *ServerInterfaceWrapper) ListErrorDeployments(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListErrorDeployments(ctx)
	return err
}

// ListUniqueChallenges converts echo context to params.
func (w *ServerInterfaceWrapper) ListUniqueChallenges(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUniqueChallenges(ctx)
	return err
}

// ReloadChallenges converts echo context to params.
func (w *ServerInterfaceWrapper) ReloadChallenges(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReloadChallenges(ctx)
	return err
}

// RetryDeployment converts echo context to params.
func (w *ServerInterfaceWrapper) RetryDeployment(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RetryDeployment(ctx)
	return err
}

// ListTeamDeployments converts echo context to params.
func (w *ServerInterfaceWrapper) ListTeamDeployments(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTeamDeployments(ctx)
	return err
}

// TerminateAdminInstance converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateAdminInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateAdminInstance(ctx)
	return err
}

// TerminateAllAdminInstances converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateAllAdminInstances(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateAllAdminInstances(ctx)
	return err
}

// DeployInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeployInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployInstance(ctx)
	return err
}

// ExtendInstance converts echo context to params.
func (w *ServerInterfaceWrapper) ExtendInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExtendInstance(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceStatus(ctx)
	return err
}

// TerminateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateInstance(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/admin/config-check", wrapper.ConfigCheck)
	router.POST(baseURL+"/admin/deploy", wrapper.DeployAdminInstance)
	router.POST(baseURL+"/admin/deploy-all", wrapper.DeployAllAdminInstances)
	router.GET(baseURL+"/admin/error-deployments", wrapper.ListErrorDeployments)
	router.GET(baseURL+"/admin/list-unique-challs", wrapper.ListUniqueChallenges)
	router.POST(baseURL+"/admin/reload-challs", wrapper.ReloadChallenges)
	router.POST(baseURL+"/admin/retry-deployment", wrapper.RetryDeployment)
	router.GET(baseURL+"/admin/team-deployments", wrapper.ListTeamDeployments)
	router.POST(baseURL+"/admin/terminate", wrapper.TerminateAdminInstance)
	router.POST(baseURL+"/admin/terminate-all", wrapper.TerminateAllAdminInstances)
	router.POST(baseURL+"/deploy", wrapper.DeployInstance)
	router.POST(baseURL+"/extend", wrapper.ExtendInstance)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/status", wrapper.GetInstanceStatus)
	router.POST(baseURL+"/terminate", wrapper.TerminateInstance)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/cNvL/KgP9/0ASQF47TYrD+V6lcZLbw6FXJA4CXBIsuOJoxVoiFZJysg32ux84",
	"1LOo9Tq13bjoO2k1JIczv3ngj/s1SlRRKonSmuj0a2SSDAtGj894IeQZlrnavsZPFRrrfi21KlFbgSST",
	"MIsbpbfumaNJtCitUDI6jc4zhOYrqBSse89YnqPcIFgFnGZeRHFktyVGp5GxWshNtIujVm4lWYHhud2X",
	"6827iyONnyqhkUen7zvVJ+t9bIeq9a+YWKfST1V+8Z8SNXMqvEZTKmkwYI9mJnoTFgt6+H+NaXQa/d9x",
	"Z+zj2tLHz5shz2uF2tl3rR5Ma7YdWMasElVJ8kgtI6TFDWonVaAxbIO9jzM2aAQDE/d/ClpkXu+9KDnA",
	"2Tfpt7/w27dDgdIuZapu2kVxlCgpMXH7W4l6gYmM3xnyFa98HK0MJkpyM7XQWS0BQkItBEbIBIG3GwFj",
	"mbbIe6bqxUC7GA0L+8CKAskBvUk/MwOJRlZPnCpdMBudRpxZPHIDQg7HL6XQaFbMThd6l6EcL1LLL+Dn",
	"Ks8hVRoqKT5VfRlz+OrGMluREVFWhcMGWcZ9jSNdSemfjFVl6R4/fju02sUmBt7n3hAgX2it9BSHe1NX",
	"eJJbh7ZHw8HO/TYEuZ2serufopVEoBaBVKuCVk6ZyJH3FAimJMHDk/b0Xp6FI6nUeClUZVYdzqbz+G+w",
	"xlTpSUxZzaQRThq5S3G0kwUsJRfOOQY+Z2gz1MDqUaA0WNSFkMwiMMorZFchodRqo9FQfATwvgflcWSR",
	"Fas5U7iPIDhKK1KBegEvitJuwY/uBekxc43ROFQna1UlvzZscmYs1AMPxc4odgWP4g7ygQBubDB17BiF",
	"A+gPNhQK6NeYK8bbrsDMtwNCcvyCAS/8XBVr1K4qtlqTy52laBCw1KKmd03LhRFrLkRZhhZotYNU5Ggg",
	"x9SCqmxTiGkRN+dBndsbv0w76bRhG/um3ninYdiQVm+7pDbbu/iwCGPZf3OxVqJ2KIIjeODB9sD9qt0a",
	"PfTF8KCNNxJo38I5Jnaz5VgLayzU5STq2wzFmWVrZnAByxSksi6ELwVHHoPtdP0s8hzWzgcpao28G9/g",
	"tEkyD0NJQsl8+6ifE7wQAb6WoRrllA7mhk7z2QyxPGuA0k9utTVDUBz5f7hEyPcTSE28XjKbTbX7hdls",
	"2k06kAdzk0ZmQtB5l21B+FRUI/TqPpQUaqcMborctud4cEDvSB2T7yooDZ5+Pbg1syhNf9zIr64HbDoW",
	"QJZk0A4BxrmBh7jYLGL4ED05KT5E7uFx9iF6tNi7mlm53LIvxXWiPg25AmMzYfqVHI4eg0ihkrkoxGyr",
	"O+3/Ak1f3C+SlOeDUeBLXLBiUYUmDYUBNu1YXTxK1W8/1krlyGS4dztHVnRZbg88uhUOP1SPesLASfru",
	"WoFRvHT1t7+xadw4x2JSaWG3b9yuvDHWyDTqZ5XNureXTSD869258zNJR6f1106hzNoy2rmJmzAb7vzZ",
	"L0vam9fL7fT5+ct+Ka6M+/GZNGKdU7AJm7uJX7H8kknxG8JSGstkQqteojZ+4pPF3xaPndFViZKVIjqN",
	"nixOFk+imLIHbcyb8jhRMhWboyTD5ML9XCpf+lTDvSy5q+Mk9ZyEnHU9dGieH05OAnVfFUUlXbPpK43N",
	"4L9bmYCpkgSNSavcaff05PF06FvJKpspLX5D7oWeTIVeKr0WnKOEIyDaDBhNDK3jd3H0Y0izpbSoJcvB",
	"oL5E7VvjgfOj0/dDt7//uPsYR6YqCuYONRGZAZLwFmmq2rZ1RZy1qg8a0r/xY+Sxi8b+pPi2TtYWPfHE",
	"yjKvFzz+ta4nPgCvCs8AtbgbxonVFe4mrv0hwBR0+afWlGxf2sZdQaNfslxwqNeGY3grL6T6LKFrEJdn",
	"dwCJpyd/37sjlmtkfAv4RRhreiC6ES+8qLG2i0ca3AAo/Sa6MtE1JQ99zqR+bYrOI5bnVyI0zwcgNVEY",
	"KDdipDDxGzCaEwywU/c4sTQ+zPOJF82sG2mdo1HN3mCgFXqFlubuyfq8Vbf5NFMMQiZ5xV3hGRAgzulD",
	"cPxbGDsihMxMdTgYGQc1GyEWanoUnADG6UuNIG2rb7E7g8x3n0bIRmOQCFnbrDkPzkAxF8YeeeQeEXL7",
	"WJxi5y1JdgTGnWDnGrc/8wiaROc9TjqtxwOb6lzr2Z+eV5t6MdTHc1JDNsnRSEQtcGEugEleE241AVRg",
	"4W58PBMEY8LIZsxCwqRU1nEVJdPG0Rh0dGMWeOUBgcCkovNSu/QD014nHUtWYAxMY3PKJjUcXJE3fFcD",
	"vX/Q22gyQ4NrOololeHBnwuNiXX76HTVyGrCJam0RmlrWwgDF1haUuHHkxP3rtFWWvrj5jBOxiTf742R",
	"faExSygGIqF29J+in58B7RD+Vm97RXZfBDiijw0IK4dUMUmjC3hTYiLSbUPIMdNRhkr3CcIQLgac5S0d",
	"G2aY0W89Onjb7Dk13HZ59KeQRoFBE0A86chDd3IgeXr7Gz8b7jJVlbxXTUkTUxNWfLYTsciKG+mJGw4v",
	"hpriA0KH5/hi2GhVuXKy3noKi4b29Gt4zmDvPCLk7qT9mSMBr9H89E1VoqaN/9VB7++gxziZx21zdTJ7",
	"JD9vRL5n3ihQqBu9XaW707ahTrGjawE1uDkbZcQbB8V5d7d+OEHTgmE/R9MB4mqa5uQPomls3/n3nqfp",
	"efNAquYwJviWg/lPxP8exuL2/rxC9qCr6PvI6Xa5QjQQIVjRlSafh9UL+j6A1S2lg9GVc6gJba98SSns",
	"Hx7z7Sx0nvvztB80aP2sUoBM59sYCvalf72r3a2yownQJotH14DVVYXiNpOK95X/s0NjKpUOTpLe6Rmy",
	"3Ga9jnbo81do/+klfqe7h5fC3Z33lX8TnPr+DepLkaA7BHvtt2PbDEzh9Qd/J0l77laf23MD8jfNX6v+",
	"QKh7CfqXisBL5LeDwO8+fbmz1fB+hs7Uzp/X6XO/v6p4893tXfSdwSKy2/1vAGfMsqmRMgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
